ccswbs/ugnext

- components/layout.js
Updating the "skip to content" link styles to match what is on gus
> Update "skip to content" link styles

- data/yaml/programs/certificate-and-diploma.yml
- data/yaml/programs/undergraduate.yml
Updating URLs and adding missing programs.
Changes:
- Equine Care & Management url updated
- Environmental Geomatics url updated
- Added Honours Agriculture program to undergraduate
Preview link: https://deploy-preview-11--ugnext.netlify.app/programs/undergraduate
> Program search data update

- data/yaml/programs/undergraduate.yml
Adds the listed programs to the program search
Test Plan:
- Go to https://deploy-preview-22--ugnext.netlify.app/programs/undergraduate
- Ensure both new programs are present in the search
> Add Biological and Medical Physics and Mechatronics Engineering programs

- components/select.js
- components/text-input.js
- data/yaml/programs/certificate-and-diploma.yml
- data/yaml/programs/graduate.yml
- data/yaml/programs/index.js
- data/yaml/programs/schema/program.schema.json
- data/yaml/programs/undergraduate-degrees.yml
- data/yaml/programs/undergraduate.yml
Making various changes to the program search based on feedback.
Changes to Undergraduate Programs:
- Added "Earth Observation and Geographic Information Science" program
- Removed "Environmental Biology" program
- Removed "Landscape Architecture" program
- Removed "Environmental Geomatics" program
- Changed "Doctor of Veterinary Medicine" bachelor to have its own type.
- Removed "Veterinary Medicine" program
- Removed duplicate bachelor programs
- Added tags to several programs
Changes to Graduate Programs:
- Added thesis-based to "Food, Agricultural and Resource Economics" types
- Added thesis-based to "Rural Planning and Development" types
- Added thesis-based to "Environmental Sciences" types
- Added thesis-based to "Landscape Architecture" types
- Removed course-based from "Rural …
> Program Search updates

- data/yaml/programs/graduate.yml
- pages/programs/graduate.js
CSAHS has requested some changes to the programs search.
List of changes:
- Change label in degree type dropdown from Masters to Master's
- Remove MAN from the degrees associated with Family Relations and Applied Nutrition
- Add thesis-based to Public Issues Anthropology
- Add three new programs: Relational and Family Therapy, Psychotherapy, Mental Health
- Remove Relational and Psychotherapy Training Program
Test plan:
1. View changes at https://deploy-preview-26--ugnext.netlify.app/programs/graduate
> Program search updates from CSAHS

- data/yaml/programs/undergraduate-degrees.yml
- data/yaml/programs/undergraduate.yml
We got requests for changes to the program search from the College of Arts.
List of changes:
- Remove "European Studies" from undergraduate
- Rename "Classical Studies" to "Classical and Modern Cultures" in undergraduate
- Add "Bachelor of Arts, General" to undergraduate
Test Plan:
1. Go to ⁠https://deploy-preview-33--ugnext.netlify.app/programs/undergraduate
2. Ensure changes appear
> Program search College of Arts changes

- data/yaml/programs/undergraduate.yml
Original request: https://dev.azure.com/uoguelph/CCS/_sprints/taskboard/WDS%20Team/CCS/Sprint%202024.25?workitem=85389
- Update links for Creative Writing and Music
- Remove Spanish and Hispanic Studies major
- Remove Studio Art minor
- Update tags for Creating Writing, Music, and Studio Art
- Go to https://deploy-preview-37--ugnext.netlify.app/programs/undergraduate
- Ensure links for Creative Writing and Music go to the program pages rather than the calendar
- Ensure major option no longer appears for Spanish and Hispanic Studies
- Ensure minor option no longer appears for Studio Art
- Ensure Creative Writing, Music, and Studio Art come up in search results for the new tags
> Undergraduate program updates from COA

- data/yaml/programs/graduate.yml
Small update to URLs for graduate programs in the program search:
- Planning
- Wildlife Biology
> Update URLs for Planning and Wildlife Biology programs

- components/home/rankings.js
Update stat on homepage to match production homepage
Update stat on homepage to match production homepage
- [n/a] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
None
1. Visit deployment URL https://deploy-preview-51--ugnext.netlify.app and confirm all content matches what is currently on the live website at https://www.uoguelph.ca
Insert steps. Include URLs of Netlify test site and Drupal multidev.
> Update stat on homepage

- components/home/three-campuses.js
Fix link on homepage
Fix link on homepage
None
Confirm Guelph Campus link goes to correct link (compare with live page)
> Fix link on homepage

- components/layout.js
Update meta description
Update meta description
None
Check meta description - should match live
> Update meta description

- azure-pipelines.yml
- Remove assetPrefix setting
- Update azure-pipeline method for ugnext build
- Remove assetPrefix setting
- Update azure-pipeline method for ugnext build
- [n/a] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
None
1. Check next.web.uoguelph.ca and confirm everything works
2. Confirm the PR deployment works at https://deploy-preview-62--ugnext.netlify.app/programs/undergraduate
> Update azure-pipeline method for ugnext build

- components/home/rankings.js
Update home page rankings.
Brief description of the proposed changes
Update rankings.js
N/A
1. Go to [homepage](https://deploy-preview-64--ugnext.netlify.app/)
2. Scroll to Our Rankings block
3. Ensure changes are present
> Update rankings.js to reflect the latest university rankings and improve link accuracy

- components/programs/program-search-navigation.js
- data/yaml/programs/continuing-education/program-types.yml
- data/yaml/programs/continuing-education/programs/applied-professional-sexuality-practices.yml
- data/yaml/programs/continuing-education/programs/counselling-and-human-sexuality.yml
- data/yaml/programs/continuing-education/programs/couple-and-family-therapy-studies.yml
- data/yaml/programs/continuing-education/programs/equine-business-management.yml
- data/yaml/programs/continuing-education/programs/foundations-in-professional-sexuality-practices.yml
- data/yaml/programs/continuing-education/programs/introducing-the-circular-economy.yml
- data/yaml/programs/continuing-education/programs/managing-the-employee-lifecycle.yml
- data/yaml/programs/continuing-education/programs/public-policy-and-administration.yml
- data/yaml/programs/continuing-education/programs/registered-veterinary-technician.yml
- Removed the "Counselling and Human Sexuality" program 
- Added several new programs under continuing education. 
- Updated the program navigation label to "Pre & Post University"
- Updated the type for "Public Policy and Administration."
- Added yaml files for new programs
- Updated program-types.yml to include micro credential
- Modfied Tab title in program-search-navigation.js
N/A
1. Go to https://deploy-preview-88--ugnext.netlify.app/programs/continuing-education
2. Ensure new programs appear and new type Micro-Credential appears in dropdown
> Update continuing education programs

- data/yaml/programs/continuing-education/programs/mobilizing-one-health.yml
Add new program: Mobilizing One Health
- Added new yaml file mobilizing-one-health.yml
N/A
1. Go to https://deploy-preview-89--test-ugnext.netlify.app/programs/continuing-education
2. Ensure new program appears in the search
> Add new program: Mobilizing One Health

- data/yaml/programs/graduate/programs/economics-and-finance.yml
- data/yaml/programs/graduate/programs/tourism-and-hospitality.yml
Add new graduate program: Economics and Finance; update types for Economics and Tourism programs
- Updates to economics.yml, and tourism-and-hospitality.yml 
- Added economics-and-finance.yml
N/A
1. Go to https://deploy-preview-99--ugnext.netlify.app/programs/graduate
2. Ensure new program shows
3. Ensure updates to old programs show
> Graduate Program Search Updates

- components/html-parser.js
Remove any strong tags that are within heading tags
Updated html-parser.js
n/a
Go to https://deploy-preview-97--ugnext.netlify.app/studentexperience
Ensure that the strong tags within the headings  have been removed.
Go to another page and ensure that strong tags outside of headings still work.
> Update html-parser.js to remove strong within H tags

- data/yaml/programs/graduate/programs/biomedical-sciences.yml
- data/yaml/programs/graduate/programs/engineering.yml
- data/yaml/programs/graduate/programs/mathematics-and-statistics.yml
Update types and degrees for some graduate programs
- biomedical-sciences.yml: Add thesis-based to types
- engineering.yml: Add PhD to degrees
- mathematics-and-statistics.yml: Add course-based to types
N/A
1. Go to https://deploy-preview-109--test-ugnext.netlify.app/programs/graduate
> Update graduate program types: add course-based and thesis-based where applicable

- azure-pipelines.yml
Remove caching from azure pipeline to avoid bug where old data shows
Remove caching from azure pipeline to avoid bug where old data shows
- [n/a] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
None
1. Check ugnext homepage
2. Confirm this looks the same as what is on next.web.uoguelph.ca
3. After merging, confirm stage.web.uoguelph.ca is showing the correct data
> Remove caching from az pipeline to avoid old data showing

- app/[...slug]/page.tsx
Fix /ovc/news route
Fix /ovc/news route
- [n/a] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.
None
1. Confirm front-end works
2. Confirm back-end works with draft preview
> Fix /ovc/news route

- components/client/html-parser.tsx
Improved vcard handling (fixes #161)
- Refactor vcard handling in `html-parser.tsx` so it correctly extracts links and renders them
N/A
Go to https://deploy-preview-162--ugnext.netlify.app/vpacademic and confirm the vcards in the right/secondary column are no longer blank.
> Refactor vcard rendering (fixes #161)
